### ISSUE TITLE
Features para melhoria e estudo.

### ISSUE THREAD

**Issue by jackmakiyama** [PHPMT/PseudoORM#1]
E aí pessoal tudo bom?

Penso que temos algumas features que podemos lançar nesse projeto com o intuito de melhorá-lo e estudarmos juntos... =D...

A princípio podemos investir nesses caras:
- Standards
  - PSR4 - Autoload e namespaces.
  - PSR2 - Code standard.
- Object Calisthenics
- Testes

**Comment by EvandroMohr** [comment]
Massa Jack. É uma boa proposta.

**Comment by enieber** [comment]
Qual seria a ordem de prioridade?

**Comment by jackmakiyama** [comment]
IMHO PSRs que já foram resolvidas com uma PR e depois testes. O que dizem?

**Comment by EvandroMohr** [comment]
Acho que testes seria uma boa.

**Comment by diegomatias** [comment]
Loading .... Nunca entendi github direito. Acho que agora é uma boa hora para começar.

**Comment by EvandroMohr** [comment]
É a hora Diego, de quebra aprende um bocado de coisa

**Comment by enieber** [comment]
@jackmakiyama e @EvandroMohr  bora passar isso para  Projects do proprio github?

**Comment by EvandroMohr** [comment]
Como funciona? sou meio noob no github =/

**Comment by enieber** [comment]
é igual ao trello mas só que é no proprio repositorio

**Comment by EvandroMohr** [comment]
manda bala =)

**Comment by enieber** [comment]
eu não tenho permição para criar um projeto.... :(

**Comment by enieber** [comment]
essa issue pode ser fechada e abrir uma só para implementação dos Autoloads  e namespaces?
