### ISSUE TITLE
Hangout

### ISSUE THREAD

**Issue by jackmakiyama** [PHPMT/PseudoORM#20]
E aí pessoal, abri aqui pra centralizar e conseguir marcar um próximo hangout pra analisar e executar as issues em aberto.

Eu posso nos finais de semana ou dias de semana a partir das 23h(Cuiabá).

O que dizem?

Pessoal que confirmou foi o @enieber @f0ntana e @EvandroMohr todos a mais são bem vindos... ^^

**Comment by EvandroMohr** [comment]
Estou livre todas as noites à partir das 18h horário de cuiabá/fortaleza

**Comment by f0ntana** [comment]
Livre! all day, today can be no problems

2016-10-25 16:36 GMT-03:00 Evandro Mohr notifications@github.com:

**Comment by enieber** [comment]
@jackmakiyama @f0ntana @EvandroMohr bora fazer hoje as 23:30 horario de cuiaba? ou fica muito tarde?

**Comment by EvandroMohr** [comment]
pra mim tá bom é o mesmo horário daqui

**Comment by f0ntana** [comment]
hoje eu tenho compromisso ;// devo chegar depois dessa hora,

se for hoje não garanto participar de toda

2016-10-27 14:13 GMT-03:00 Evandro Mohr notifications@github.com:

**Comment by jackmakiyama** [comment]
Vocês topam no sábado então?

As 14h é suave pra mim.

**Comment by EvandroMohr** [comment]
Pra mim, tá ok

**Comment by f0ntana** [comment]
pra mim excelente

2016-10-27 17:20 GMT-03:00 Evandro Mohr notifications@github.com:

**Comment by enieber** [comment]
pra mim ta meio corrido, mas pode fazer vcs que eu acompanho depois...

**Comment by jackmakiyama** [comment]
@PHPMT/members , tudo confirmado para hoje as 20h?

**Comment by f0ntana** [comment]
Confirmed

Em segunda-feira, 31 de outubro de 2016, Jack Makiyama <
notifications@github.com> escreveu:

**Comment by enieber** [comment]
Confirmed

**Comment by EvandroMohr** [comment]
confirmed

**Comment by enieber** [comment]
ja da pra abrir uma outra issue @PHPMT/members
