### ISSUE TITLE
Adicionar PSR4 - Autoload e namespaces.

### ISSUE THREAD

**Issue by enieber** [PHPMT/PseudoORM#23]
Essa issue foi aberta em continuação da issue #1

**Comment by EvandroMohr** [comment]
Falta fazer algum desses? Acho q já está adequado, não acha @jackmakiyama

**Comment by jackmakiyama** [comment]
Está, mas esses caras me incomodam:

https://github.com/PHPMT/PseudoORM/blob/master/index.php#L29-L33

**Comment by EvandroMohr** [comment]
vdd, mas como eles funcionam como annotations, parece que o autoload não carrega se não for assim. como resolver? =/

**Comment by jackmakiyama** [comment]
Vamos procurar uma solução. Acho que agora temos que automatizar os testes que estão no index.
