### ISSUE TITLE
Hangout

### ISSUE THREAD

**Issue by enieber** [PHPMT/PseudoORM#31]
eai @PHPMT/members  bora fazer mais um hangout para discutir sobre o andamento do projeto? Acho que seria bom nos montar uma pauta, nem que seja pequena...

**Comment by f0ntana** [comment]
Apoiado não podemos deixar morrer.

2016-11-17 13:21 GMT-03:00 Enieber Cunha notifications@github.com:

**Comment by EvandroMohr** [comment]
quando?

**Comment by f0ntana** [comment]
por mim pode ser a noite qualquer horário..

2016-11-17 13:24 GMT-03:00 Evandro Mohr notifications@github.com:

**Comment by enieber** [comment]
essa semana pra mim ta bem corrido, mas semana que vem vou estar mais de boa

**Comment by EvandroMohr** [comment]
massa por mim pode ser semana que vem tbm.

**Comment by jackmakiyama** [comment]
só posso nos finais de semana ou nos dias de semana depois das 00h...

**Comment by jackmakiyama** [comment]
Bom mesmo assim, o ambiente já está okay, agora podemos partir para os testes os testes funcionais e o ambiente do travis.

O que dizem?

**Comment by EvandroMohr** [comment]
temos que marcar o hangout.
e aí galera, diga a disponibilizade de vcs. =)

**Comment by enieber** [comment]
bora fazer hoje as 22h horario de Cuiaba?

**Comment by f0ntana** [comment]
Combinado

2016-11-22 9:21 GMT-03:00 Enieber Cunha notifications@github.com:

**Comment by EvandroMohr** [comment]
pra mim não dá =/

**Comment by jackmakiyama** [comment]
Pra mim também não rola.

**Comment by enieber** [comment]
qual dia da pra vc @EvandroMohr ?

**Comment by jackmakiyama** [comment]
Dia de semana se for muito breve tipo uns 30 minutos eu consigo as 18h30.

**Comment by EvandroMohr** [comment]
eu posso durante a noite na semana e fds livre. só não posso hoje.

**Comment by enieber** [comment]
pode ser quarta as 18:30 então? só para conversarmos como o projeto vai andar daqui pra frente, ai definimos uma pauta de assuntos pra não perdemos os foco

**Comment by EvandroMohr** [comment]
pode ser. amanhã 18h30 horário de cuiabá

**Comment by f0ntana** [comment]
ok

2016-11-22 10:25 GMT-03:00 Evandro Mohr notifications@github.com:

**Comment by jackmakiyama** [comment]
Pessoal,

Antes, vamos resolver essas PRs. Se não, não rende a parada.

**Comment by EvandroMohr** [comment]
vdd. to com problemas no composer. =/

**Comment by enieber** [comment]
@PHPMT/members  bora começar?
