### ISSUE TITLE
Incorporar script de criação do BD à classe GenericDAO

### ISSUE THREAD

**Issue by EvandroMohr** [PHPMT/PseudoORM#4]
Mesclar funcionalidade do PseudoORMCreator com a classe GenericDAO.

**Comment by jackmakiyama** [comment]
:+1: 

acho interessante, nem que seja como dependencia, mas a frente pode ser aqui. =D

**Comment by EvandroMohr** [comment]
Ja fiz. Está com IoC. Mas depois dá pra extrair.

**Comment by jackmakiyama** [comment]
:beers:
