### ISSUE TITLE
linguagem usada para o projeto PT-BR ou EN ?

### ISSUE THREAD

**Issue by enieber** [PHPMT/PseudoORM#42]
Votação proposta pelo @jackmakiyama 

:+1:  => PT-BR

:heart:  => EN

**Comment by jackmakiyama** [comment]
Considerem o que o @filipedeschamps apresenta aqui:

https://www.youtube.com/watch?v=xWbuHZcS8gA

**Comment by f0ntana** [comment]
👍

**Comment by enieber** [comment]
@PHPMT/members vamos fechar essa issue?
