### ISSUE TITLE
Ambiente de desenvolvimento padrão

### ISSUE THREAD

**Issue by jackmakiyama** [PHPMT/PseudoORM#6]
Vocês acham legal adicionarmos um vagrant aqui parar padronizar o ambiente de desenvolvimento?
Com o [Vaprobash](https://github.com/fideloper/Vaprobash) isso é muito prático.

**Comment by EvandroMohr** [comment]
Eu particularmente não faço ideia de como se usa. =/

**Comment by jackmakiyama** [comment]
é uma vm de no virtual box provisionada pelo vagrant, simples e todos ficamos com o mesmo ambiente. =D

**Comment by EvandroMohr** [comment]
Manda bala. Bom que aprendo tbm.

**Comment by enieber** [comment]
cara muito massa, mas em casos parecido com o meu, quando já se usa o ubuntu não acho q seria uma boa usar uma vm pra desenvolver... poderia colocar como uma indicação de se usar

**Comment by EvandroMohr** [comment]
Eu uso OSX e Ubuntu. Mas preferencialmente Ubuntu.

**Comment by diegomatias** [comment]
No momento estou usando o MintDebian... já ouviram falar do docker ele emula uma VM compartilhando o kernel do sistema hospedero com o sistema convidado, pode ser bem interessante.

**Comment by jackmakiyama** [comment]
é exatamente o por isso que é interessante padronizar o ambiente de desenvolvimento... =D... Como cada um tem o que quer na maquina host, o VM é isolada com configs apenas necessárias para rodas o projeto.

Docker é interessante mas eu não saco nads dele.. kkk mas curto demais o AZK =D

**Comment by enieber** [comment]
da pra usar o Vaprobash sem o VM?

**Comment by jackmakiyama** [comment]
Vaprobash é uma forma que automatiza o provisionamento do Vagrant, não tem
como fugir da VM. Mas a VM é uma box ubunto limpa e o com o Vaprobash
provisionamos oque precisamos, no projeto versiono apenas um arquivo de
texto Vagrantfile... E quem for usar com vagrant e virtual box instalado
apenar digita `vagrant up` no terminal e pronto. Isso é bom que
configurações de ambiente não precisam ser feitas localmente.

**Comment by enieber** [comment]
agora entendi.. sendo assim fica muito melhor para padronizar... boa ideia...

**Comment by EvandroMohr** [comment]
É Enieber, ambientes diferentes dá muita dor de cabeça. Dá conflito de encoding de arquivos, carrega coisa desnecessária. Fica mais complicado de debugar, já que tem coisa que funciona no pc de um e no outro nao....

**Comment by enieber** [comment]
sei como é... trabalho com o windows e em casa com ubuntu, sei bem como é complicado isso...

**Comment by enieber** [comment]
Docker baseado em uma imagem pequena semelhante ao Alpine

**Comment by EvandroMohr** [comment]
Preciso aprender essas coisas =(

**Comment by enieber** [comment]
eu sei só o basico, o @jackmakiyama que ja ta usando o docker pra desenvolver

**Comment by jackmakiyama** [comment]
@enieber vamos fazer um hangout e ver o que conseguimos resolver dessas paradas. =D.

Quem topa?

**Comment by EvandroMohr** [comment]
eu topo, só dizer o dia =)

**Comment by EvandroMohr** [comment]
Acho que deveriamos padronizar a linguagem. Tem coisa em portugues e em ingles.

Como serão os comentários de commits, as issues, os PRs? tudo em ingles ou tudo em portugues?

**Comment by jackmakiyama** [comment]
Cara, pode ser em português por ser para fins didático.

**Comment by enieber** [comment]
por mim pode ser em uma sexta ou em uma quarta o hangout

**Comment by jackmakiyama** [comment]
Sexta é dia de cachaça caraí! kkkkk

**Comment by enieber** [comment]
vai ser docker mesmo né @PHPMT/members ?

**Comment by jackmakiyama** [comment]
Sim, assim que conseguirmos rodar 100% vamos fechar essa issue.

**Comment by enieber** [comment]
tem dois PRs para ser analizados sobre essa issue, o meu #30  ainda falta algumas melhorias
