### ISSUE TITLE
Testes

### ISSUE THREAD

**Issue by jackmakiyama** [PHPMT/PseudoORM#9]
Galera com o ambiente de desenvolvimento padronizado, podemos entrar nos testes.
Primeiro eu penso em automatizar os testes funcionais do index.php.
Outra coisa, aqui é um ambiente mais complexo, então penso em fazer pair, o que me dizem?

Ambiente para pair:
- Tmux(tmate)
- Vim
- Audio chamada(Skype)

É tranquilo pra vcs?

**Comment by EvandroMohr** [comment]
Por mim é tranquilo.

**Comment by enieber** [comment]
@jackmakiyama  poderia adicionar uma imagem docker com todas as dependencias para facilitar os testes e recomeçar a faze los.

**Comment by jackmakiyama** [comment]
@enieber sim, vamos fazer isso!

**Comment by EvandroMohr** [comment]
Não deixa a ideia morrer =)

**Comment by enieber** [comment]
Qual seria as dependencias para começar a testar?

**Comment by jackmakiyama** [comment]
Guys, querem fazer hangout?

@f0ntana está convocado também. 😝

**Comment by f0ntana** [comment]
Boa.. vou me atualizar.

**Comment by enieber** [comment]
acho que da para começar os testes assim que fechar a issue #6 ai da para fazermos um hangout para começarmos os testes
